Fix AI panel not closing properly
cardstack/boxel pull request #1887
Opened 2024-12-05 13:29 UTC by FadhlanR

https://github.com/user-attachments/assets/17ebbcc8-6596-4695-aba4-f41eabcbbb3b

In this PR, instead of directly addressing the bug, I decided to refactor resizable-panel by forking some logic from the react-resizable-panels library. Now, the bug is fixed and the codes look cleaner.

2024-12-09 08:20 UTC, richardhjtan commented
There is some behaviour change on the resizable panel in code mode. The most noticeable one is that the data section no longer auto-hides when reduced to a certain width.

**Before**

https://github.com/user-attachments/assets/abc72907-8e7e-4998-a3f6-dadcfb934d0d

**Now**

https://github.com/user-attachments/assets/fdecfa27-5eeb-41dc-98a1-d3e65e6cbb5e

It shouldn't be considered a bug but just the decision if we need to preserve this behaviour

2024-12-09 08:21 UTC, richardhjtan commented
The AI assistant chat max-width has changed, but looks more natural to me

**Before**
![ai-chat-max-width-before](https://github.com/user-attachments/assets/009e8eba-8aba-43ea-985e-e97ee2e9787c)

**After**
![ai-chat-max-width-now](https://github.com/user-attachments/assets/764e466d-56e7-4e7a-b6ee-1be1707a0197)

2024-12-09 15:42 UTC, lukemelia requested changes
File names should be consistent with repository style (dasherized)

2024-12-09 15:45 UTC, lukemelia commented on packages/host/app/components/operator-mode/code-submode.gts
>  const ApproximateRecentPanelDefaultFraction =
If we're going to make this out of 100, rename the constant to `ApproximateRecentPanelDefaultPercentage`

2024-12-09 16:18 UTC, FadhlanR commented
> There is some behaviour change on the resizable panel in code mode. The most noticeable one is that the data section no longer auto-hides when reduced to a certain width.
> 
> **Before**
> 
>  resize-panel-before.mov 
> **Now**
> 
>  resize-panel-now.mov 
> It shouldn't be considered a bug but just the decision if we need to preserve this behaviour

Thanks for checking, I forgot to remove the collapsible tag for the code panel. I've updated please check it again.

2024-12-09 16:18 UTC, FadhlanR commented
> The AI assistant chat max-width has changed, but looks more natural to me
> 
> **Before** ![ai-chat-max-width-before](https://private-user-images.githubusercontent.com/30404522/393755977-009e8eba-8aba-43ea-985e-e97ee2e9787c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NjAzNjEsIm5iZiI6MTczMzc2MDA2MSwicGF0aCI6Ii8zMDQwNDUyMi8zOTM3NTU5NzctMDA5ZThlYmEtOGFiYS00M2VhLTk4NWUtZTk3ZWUyZTk3ODdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDE2MDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNzI5M2IxZDJmZWJhNzAyZTg2MzUxODc0ZDY2ZDNkM2QwMzBiOTQyZjVkZDc4ZWRhMzhkZTdjZDYxNDM4OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D0FqaiVqnD7e9j7Yc0ba86QPCvaUTttn08le5meuVVA)
> 
> **After** ![ai-chat-max-width-now](https://private-user-images.githubusercontent.com/30404522/393755987-764e466d-56e7-4e7a-b6ee-1be1707a0197.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NjAzNjEsIm5iZiI6MTczMzc2MDA2MSwicGF0aCI6Ii8zMDQwNDUyMi8zOTM3NTU5ODctNzY0ZTQ2NmQtNTZlNy00ZTdhLWI2ZWUtMWJlMTcwN2EwMTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDE2MDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4M2ZjNmJmMTQxZWFjMTA2NWNmMGFlZTk1NTg0MGQyNzFjZTZjOTZlNGRkYzc1NWRiOWIwMzZjOWE5MjY3YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2BQ_vjcqVweGpf_AvAWsxIfcv-q2PsZ2p_k62bmxOsc)

I think the previous min size is too small, so I updated it.

2024-12-09 16:19 UTC, FadhlanR commented
> File names should be consistent with repository style (dasherized)

Updated

2024-12-09 22:21 UTC, burieberry reviewed
Looks good overall. In terms of ai-chat panel size, I noticed it starts getting cropped from the right when the viewport gets too small and some of the buttons become unreachable. I recommend not letting it get smaller than approximately 300px. The default size of the ai panel in the designs seems to be around 366px.

Buttons cropped on the right-side when too small:
<img width="951" alt="cropped-ai-chat" src="https://github.com/user-attachments/assets/b787dc7a-abf9-44e4-848a-a884691e8e71">

2024-12-10 03:20 UTC, lukemelia approved these changes
The minSize of 25 for the AI assistant panel feels too large on a wide display. Are we limited to percentage-based min sizes?

2024-12-10 14:15 UTC, FadhlanR commented
> The minSize of 25 for the AI assistant panel feels too large on a wide display. Are we limited to percentage-based min sizes?

Yes, the pixel-based constraints added significant complexity, which is why we are limited to percentage-based constraints. However, I’ve adjusted the panel widths in submode-layout. It may not work perfectly when resizing the window, but when the AI panel is closed and reopened, it will open with a better size. cc: @burieberry

2024-12-10 15:03 UTC, lukemelia commented
I think there used to be a threshold behavior where if you shrank a panel below a certain threshold and it was collapsible it would collapse. Was that intentionally removed?

2024-12-10 15:10 UTC, FadhlanR commented
> I think there used to be a threshold behavior where if you shrank a panel below a certain threshold and it was collapsible it would collapse. Was that intentionally removed?

It's still there, you can try to resize code editor panel in code submode. It will collapse once the size is lower than minSize.

2024-12-10 16:01 UTC, jurgenwerk commented
<img width="774" alt="image" src="https://github.com/user-attachments/assets/679d725f-75ca-4d9c-8c7a-cf37039021d4">

Dragging this box is glitchy:

https://github.com/user-attachments/assets/cf8dc269-fc27-4c3a-9777-55f853be8c4d

2024-12-10 16:06 UTC, FadhlanR commented
> <img width="774" alt="image" src="https://github.com/user-attachments/assets/679d725f-75ca-4d9c-8c7a-cf37039021d4">
> 
> 
> 
> Dragging this box is glitchy:
> 
> 
> 
> https://github.com/user-attachments/assets/cf8dc269-fc27-4c3a-9777-55f853be8c4d
> 
> 
> 
> 
> 
> 

I'll check the box corner.

For the glitch, i think it's expected behavior since we define the minimum size for recent files panel. So the recent files panel will only open if the cursor dragging delta is more than the minimum size. Is it better to remove the minimum size of recent files panel? cc: @lukemelia

2024-12-10 16:15 UTC, richardhjtan approved these changes

2024-12-10 16:26 UTC, jurgenwerk commented
I think the previous resize behavior of recent files felt much nicer... you could resize it to a small size and when the handle was very close to to the border, it snapped into the closed position.

Another degradation that I found - I would expect to be able to narrow this column down even further but now it snaps closed when there is still plenty of available room:

<img width="774" alt="image" src="https://github.com/user-attachments/assets/480230c1-5f20-4982-bcf9-740c7d7fc8a9">

2024-12-10 16:41 UTC, FadhlanR commented
> Another degradation that I found - I would expect to be able to narrow this column down even further but now it snaps closed when there is still plenty of available space for code:

I've updated the minimum size of code editor. Please check it again.


> <img alt="image" width="774" src="https://private-user-images.githubusercontent.com/273660/394350660-679d725f-75ca-4d9c-8c7a-cf37039021d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NDg4NjksIm5iZiI6MTczMzg0ODU2OSwicGF0aCI6Ii8yNzM2NjAvMzk0MzUwNjYwLTY3OWQ3MjVmLTc1Y2EtNGQ5Yy04YzdhLWNmMzcwMzkwMjFkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxNjM2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzhkM2JhMzVhOTQ3MjAwYjJjNThmODM4ZGVhOTU4ZTU5MTZlZDE0NWMzMzIwMzVhNTY2N2Q0MjQzNWFlYWI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qNofNXX9vVGgobYarvM03SUA7JtfdJ6YbJ22Aw9mkps">

Fixed!

2024-12-10 17:20 UTC, burieberry approved these changes

2024-12-10 21:04 UTC, jurgenwerk commented
The boxes still snap close too quickly... it feels jarring when there is plenty of space left for content and then the box just closes. 

Here is what I am experiencing:

https://github.com/user-attachments/assets/fb5b2b60-0e02-406d-b630-62d1078ea497

Here is the old behaviour where breakpoints aren't that extreme: 

https://github.com/user-attachments/assets/d0190242-b09b-4a79-ba8e-43e432c1c95a

2024-12-11 04:01 UTC, FadhlanR commented
> In my opinion the boxes still snap close too quickly. It feels odd when there is plenty of space left for content and then the box just closes.
> 
> Here is what I am experiencing:
> 
>  Screen.Recording.2024-12-10.at.21.53.29.mov 
> Here is the old behaviour where breakpoints aren't that extreme and the experience is nicer:
> 
>  Screen.Recording.2024-12-10.at.21.59.24.mov

It seems we need to introduce a minimum length in pixels. What do you think about filing separate tickets for the minimum length in pixels and the collapsed panel behavior? I believe the adjustment will take time with the current calculation logic. However, the current logic is much better than the previous one because it's more readable and provides more precise cursor positioning when dragging the panel.

2024-12-11 09:04 UTC, jurgenwerk commented
I am not actually seeing any improvement with your workaround. I am ok if issues are addressed in follow up work.

2024-12-11 09:41 UTC, merged