intoduce --delete arg to rsync. Deleted files will be removed from persistent
cardstack/boxel pull request #1986
Opened 2024-12-25 16:57 UTC by tintinthong

…ersistent

2024-12-26 14:54 UTC, lukemelia requested changes
I think we don't want to do this with the experiments realm. If we do, changes made by us will be wiped out every deploy. Seems OK for base, seed, & catalog.

2024-12-30 14:52 UTC, habdelra commented
yeah, this is what I was thinking--but we should make it an option like @lukemelia was saying so that in the experiements realm we don't blow away stuff that was added outside of git

2025-01-06 04:23 UTC, tintinthong commented
I have updated this to only use --delete with catalog, seed, base.

2025-01-06 15:29 UTC, richardhjtan approved these changes

2025-01-06 15:39 UTC, backspace approved these changes

2025-01-06 17:24 UTC, lukemelia approved these changes

2025-01-06 17:40 UTC, merged