implement filter query of side panel
cardstack/boxel pull request #1987
Opened 2024-12-26 13:49 UTC by lucaslyl

linear: https://linear.app/cardstack/issue/CS-7722/implement-account-side-panel-design

- Side panel filter list for CRM account
- Filter by value
- add icon to urgency tags

<img width="1313" alt="Screenshot 2024-12-27 at 17 01 49" src="https://github.com/user-attachments/assets/745bdc11-a80f-4b5a-9612-dd1a5e6b6591" />

2024-12-27 07:20 UTC, tintinthong requested changes

2024-12-27 07:20 UTC, tintinthong commented on packages/experiments-realm/crm-app.gts
>  const ACCOUNT_FILTERS: LayoutFilter[] = [
Can we get all the data from one place? Like the exclude status field rather than making a new copy. I already had the thought of chnaging the list of field values but I have to change it in 2 places

2024-12-27 07:20 UTC, tintinthong commented on packages/experiments-realm/crm-app.gts
> +    console.log('option', option);
Remove

2024-12-27 07:20 UTC, tintinthong commented on packages/experiments-realm/crm-app.gts
> +                contains: { 'company.name': searchKey },
Here I dono why 'company.name' is here. But it didn't seem right or general at all. I will look into it

2024-12-27 07:20 UTC, tintinthong commented on packages/experiments-realm/crm-app.gts
> +        every: [baseFilter, ...accountFilter, ...searchFilter],
Why is accountFilter here? You are changing the way the query is supposed to be generic and query supposed to be declared. You need to look into loadAllFilters and LAYOUT_FILTER to implement ur change. Not swoop it inside here

2024-12-27 07:20 UTC, tintinthong commented on packages/experiments-realm/crm-app.gts
> +        every: [baseFilter, ...accountFilter, ...searchFilter],
This may require including a different sort of data inside LAYOUT_FILTER

2024-12-27 09:13 UTC, lucaslyl commented on packages/experiments-realm/crm-app.gts
> +                contains: { 'company.name': searchKey },
following the previous code commit, you might want to search queries by company name.

2025-01-03 04:20 UTC, tintinthong approved these changes

2025-01-03 04:27 UTC, merged