WIP add freestyle to boxel-ui
cardstack/boxel pull request #302
Opened 2023-04-18 22:11 UTC by lukemelia

2023-04-19 22:30 UTC, backspace requested changes
This looks good to me although I got this error when trying to start it:

```
Directory not found: /Users/b/Documents/Cardstack/Code/boxel-motion/packages/boxel-ui/tests/dummy/app/styles
```

I created an empty file at `packages/boxel-ui/tests/dummy/app/styles/app.css` and then it started up successfully.

2023-04-19 22:30 UTC, backspace commented on packages/boxel-ui/.ember-cli.js
> +  port: 4210,
I really appreciate a default vs me having to remember my own scheme for our various Ember applications 🎉

2023-04-20 20:12 UTC, lukemelia commented
@backspace I fixed the missing directory issue, and added test coverage that would catch this in CI.

2023-04-20 22:28 UTC, backspace approved these changes
As an aside, should this be v2-ified? Does that matter in a monorepo?

2023-04-21 21:20 UTC, burieberry approved these changes
Updated versions of the css files are in host's app.css, but we can move them out of there after the merge. I'm open to flattening the component directory structure so that all the component files aren't named `index.gts`or `usage.gts`

2023-04-24 14:04 UTC, habdelra approved these changes

2023-04-24 14:46 UTC, merged