Can select one or more cards on index grid
cardstack/boxel pull request #440
Opened 2023-06-28 18:04 UTC by burieberry

- Added hover and selection styles
- Can select/unselect one or more items

Selection logic:
- For first selection, need to click on the round selection icon
- For following select/unselect actions can use the icon or can directly click on the card
- Only when there are no selected cards, clicking on the card opens the card in stack

Improvement idea:
- Select All / Unselect All options

Next step:
- Extract the card selection UI as Boxel component and use it in index card and in card catalog

<img width="847" alt="card-grid-selection" src="https://github.com/cardstack/boxel/assets/16160806/cb4ef6c2-f55a-473b-bf84-eaf854a09f3a">

2023-06-29 12:40 UTC, FadhlanR commented on packages/base/cards-grid.gts
> +  @tracked selectedCards: Card[] = [];
Can we use trackedArray here?

2023-06-29 12:42 UTC, FadhlanR commented on packages/base/cards-grid.gts
> +      this.selectedCards = [...this.selectedCards, card];
with `TrackedArray` we don't need to reinitialize `selectedCards`.

2023-06-29 13:24 UTC, lukemelia requested changes

2023-06-29 13:24 UTC, lukemelia commented on packages/base/cards-grid.gts
> +    return component?.constructor?.name === 'OperatorModeStackItem';
This seems fragile to refactoring.

2023-06-29 13:24 UTC, lukemelia commented on packages/base/cards-grid.gts
> +    return false;
```suggestion
    return this.selectedCards.some((card) => card.id === id);
```

2023-06-29 15:50 UTC, burieberry commented on packages/base/cards-grid.gts
> +    return component?.constructor?.name === 'OperatorModeStackItem';
Any suggestions? If we're moving selection to the operator mode, then we won't need this check here. I can try to move selection as part of this PR

2023-07-03 08:35 UTC, jurgenwerk commented on packages/boxel-ui/addon/components/actions-overlay/index.gts
> +  refreshLoopStartedAt: number | null = null;
I don't see these two properties being used

2023-07-03 08:35 UTC, jurgenwerk commented on packages/boxel-ui/addon/components/actions-overlay/index.gts
> +    {{#let @card as |card|}}
How come this block is needed? Can we just use `@card` in the code below?

2023-07-03 17:24 UTC, burieberry commented on packages/boxel-ui/addon/components/actions-overlay/index.gts
> +    {{#let @card as |card|}}
Sorry this PR went back to "in progress/draft" state. I was lazy to replace while just trying stuff out before fully committing to this implementation. I'll do the clean up

2023-07-12 17:42 UTC, lukemelia approved these changes

2023-07-12 17:56 UTC, merged