Dyanmically import monaco editor
cardstack/boxel pull request #470
Opened 2023-07-13 03:16 UTC by tintinthong

2023-07-13 13:19 UTC, tintinthong commented
Hmm I broke something. When swapping files from glimmer to a json file and then go back to a glimmer file, I find that it still recognises the language as json

2023-07-13 13:22 UTC, habdelra commented on packages/host/app/routes/code.ts
> +    let monacoContext = await this.monacoService.getMonacoContext(openFile);
I agree this is a really good place to load the monaco SDK :+1:

2023-07-13 13:25 UTC, habdelra approved these changes
Looks good to me. after you solve the language switching issue I think it should be good to merge

2023-07-13 14:58 UTC, burieberry approved these changes
Good improvement on syntax highlighting issue

2023-07-13 15:12 UTC, jurgenwerk requested changes

2023-07-13 15:12 UTC, jurgenwerk commented on packages/host/app/components/editor/go.gts
> +      .main { position: relative; display: grid; grid-template-columns: 15rem
CSS got reformatted here. I think we are stuck with this issue until https://github.com/prettier/prettier/pull/15087 lands but I'll try to see if we can speed this up by using a temporary fork. What do other Boxelians do right now to avoid this? I personally temporarily disable automatic formatting before committing, paste formatted code, save and then re-enable

2023-07-13 15:19 UTC, lukemelia commented on packages/host/app/components/editor/go.gts
> +      .main { position: relative; display: grid; grid-template-columns: 15rem
Same

2023-07-13 15:20 UTC, lukemelia commented
@tintinthong nice improvement. I notice we are still loading all the CSS for monaco up front. Is there a similar way to achieve chunking and deferred load for this CSS?

2023-07-14 06:20 UTC, tintinthong commented on packages/host/app/components/editor/go.gts
> +      .main { position: relative; display: grid; grid-template-columns: 15rem
Reverted here https://github.com/cardstack/boxel/pull/470/commits/846b5b12b9d4b361fa776236d826df93efc08b5e

2023-07-17 09:08 UTC, jurgenwerk commented on packages/host/app/components/editor/go.gts
> +      .main { position: relative; display: grid; grid-template-columns: 15rem
You can rebase to main now to get the proper auto formatting.

2023-07-17 09:09 UTC, jurgenwerk approved these changes

2023-07-17 13:42 UTC, tintinthong commented
> @tintinthong nice improvement. I notice we are still loading all the CSS for monaco up front. Is there a similar way to achieve chunking and deferred load for this CSS?

Hmmmm. So I looked into this. 

I thought my expectation is that the CSS would load the same time as the dynamic import (ie when I hit the /code/ endpoint) but it seems that webpack purposely loads the CSS upfront. I have proven this by removing the dynamic import and it can be seen that the CSS doesn't load (just to confirm that the CSS doesn't come from anywhere else accidentally).

I believe this has to do with webpack by default loading CSS upfront. Im still not too clear what this means whether its due to import of css files (loading of css files) or css files is injected at runtime (presumably this is not the case otherwise we wudn have this issue) or even if this is just the general expectation (since late loading of css wud generally create flickr effects in the UI)

Im gonna park this into a ticket [CS-5781](https://linear.app/cardstack/issue/CS-5781/investigate-why-css-is-loaded-before-monaco-editor-dynamic-import) to understand it more

2023-07-17 13:45 UTC, tintinthong commented
PS: There is something which I went thru in this PR that was very annoying that cause me long hours of thinking this doesn't work. I always assume that glimmerTS syntax highlighting was working. It turns out other language files worked but not glimmerTS. I also made a ticket for that https://linear.app/cardstack/issue/CS-5780/get-monaco-editor-syntax-highlighting-to-work-with-glimmerts

2023-07-17 13:55 UTC, merged