Add dynamic card chooses title
cardstack/boxel pull request #492
Opened 2023-07-23 07:05 UTC by tintinthong

2023-07-24 14:17 UTC, lukemelia requested changes
Looks promising. Can we add some tests?

2023-07-25 13:29 UTC, tintinthong commented on packages/runtime-common/text-suggestion.ts
> +export function suggestCardChooserTitle(
This function tries to make suggestions as to what text when choosing a list of cards based upon the `Filter`. Particularly, by searching for possible cases of card context like `on` or `type`. 
This function uses a recursive call when going into quantifier like `every`. But not all filters types are supported like `any` or `not` or `range`. The reason is bcos these filters dont contribute to context of the card search and possibly confound

2023-07-25 20:30 UTC, burieberry reviewed
Overall looks good, a couple of points:
- Need to use `a` or `an` depending on context: `Choose an Article card`, `Choose a Post card`
- In the LinksToMany case, the title will ask to select 1 or more cards `Select 1 or more contact cards`

2023-07-26 08:51 UTC, tintinthong commented
> Overall looks good, a couple of points:
> 
> * Need to use `a` or `an` depending on context: `Choose an Article card`, `Choose a Post card`
> * In the LinksToMany case, the title will ask to select 1 or more cards `Select 1 or more contact cards`

Great suggestions! Additionally I moved text-suggestions into host from runtime common

![Screenshot 2023-07-26 at 4 47 27 PM](https://github.com/cardstack/boxel/assets/8165111/899a6f3a-bd17-4298-b515-05657b744086)
![Screenshot 2023-07-26 at 4 47 44 PM](https://github.com/cardstack/boxel/assets/8165111/6dd37dd4-97dd-4c62-86e2-3761f6ca740d)
![Screenshot 2023-07-26 at 4 49 08 PM](https://github.com/cardstack/boxel/assets/8165111/6e075b10-8d92-4463-96f9-f21f6d69fa22)

2023-07-26 11:31 UTC, FadhlanR approved these changes

2023-07-26 12:36 UTC, tintinthong commented
It should be "Choose one or more Friend Cards" (+s) now

2023-07-26 14:12 UTC, burieberry approved these changes

2023-07-26 14:32 UTC, merged