More card field separation refactoring
cardstack/boxel pull request #573
Opened 2023-08-25 19:28 UTC by habdelra

Enforcing contains() only accepts FieldDefs and many renamings

2023-08-25 19:42 UTC, habdelra commented
There are a bunch of cards on the draft realm that aren’t working that need attention still…

2023-08-25 22:15 UTC, backspace requested changes
V minor suggestions

2023-08-25 22:15 UTC, backspace commented on packages/base/room.gts
> +class MesageField extends FieldDef {
```suggestion
class MessageField extends FieldDef {
```

Hopefully `Rename Symbol` makes this easy.

2023-08-25 22:15 UTC, backspace commented on packages/host/app/lib/matrix-handlers/index.ts
> +// the RoomObjectiveCard and the interior card is the RoomField.
```suggestion
// the RoomObjectiveCard and the interior field is the RoomField.
```

I think?

2023-08-28 14:01 UTC, lukemelia approved these changes

2023-08-28 15:44 UTC, backspace approved these changes

2023-08-28 16:54 UTC, merged