Styling containsMany primitive field within card
cardstack/boxel pull request #650
Opened 2023-09-15 11:03 UTC by FadhlanR

Ticket: CS-6022

https://github.com/cardstack/boxel/assets/12637010/b67604c4-1369-4cb1-b134-fa2ea9ef202c

2023-09-15 13:45 UTC, habdelra commented
the padding looks uneven. in the ticket there is an even amount of padding for all side. but in your PR the padding for the left and right is about half as much as the padding for the top and bottom.

2023-09-18 05:59 UTC, FadhlanR commented
> the padding looks uneven. in the ticket there is an even amount of padding for all side. but in your PR the padding for the left and right is about half as much as the padding for the top and bottom.

Updated.
<img width="594" alt="Screenshot 2023-09-18 at 12 57 55" src="https://github.com/cardstack/boxel/assets/12637010/90bdf8f3-2c9b-48c4-86b1-56b88b955256">

2023-09-18 15:10 UTC, lukemelia approved these changes

2023-09-18 15:12 UTC, lukemelia requested changes
Looks like Percy is showing some unintended changes

2023-09-19 16:05 UTC, lukemelia approved these changes

2023-09-19 17:00 UTC, merged